file:
  upload-path: /files/upload
  result-path: /files/result
  template-path: /files/template
task:
  parallel-thread-num: 8
  begin-multi-thread-threshold: 400000
executor:
  core-pool-size: 10
  max-pool-size: 100
  keep-alive-time: 60
spring:
  datasource:
    url: jdbc:mysql://172.16.6.2:3306/lhcdo?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: qaz7852336
    druid:
      initial-size: 10
      max-active: 50