file:
  upload-path: /Users/wangyongxin/Desktop
  result-path: /Users/wangyongxin/Desktop/result
  template-path: /Users/wangyongxin/Desktop
task:
  parallel-thread-num: 4
  begin-multi-thread-threshold: 2000
executor:
  core-pool-size: 10
  max-pool-size: 50
  keep-alive-time: 60
  queue-capacity: 100
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lh?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: wyx123
    druid:
      initial-size: 5
      max-active: 10
  jpa:
    show-sql: true